apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-build-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-build-2
    app.kubernetes.io/part-of: demo-build-1
  name: demo-build-2ilzn
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: demo-build-2
    weight: null
status: {}
