apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-build-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-build-2
    app.kubernetes.io/part-of: demo-build-1
  name: demo-build-2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: demo-build-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: demo-build-2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/otikhomi-tenant/demo-build-1/demo-build-2@sha256:1fa5c6ca1e6c17dd88f14af4bd3f16906e15812c494cf2ff61c2a3efb6f22409
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
